### PR TITLE
docs: Add note about clog-cli

### PR DESCRIPTION
**Pull request by kentcdodds**
So the whole world (that uses a Mac) can get this more easily :-)

### CODE REVIEW

**Comment by PascalPrecht** [comment]
Can't people on windows also install packages via npm?

**Comment by cburgdorf** [comment]
@PascalPrecht the problem is that they need different binaries and somehow one has to tell npm which binary to use for which platform.

**Comment by cburgdorf** [comment]
Thanks! Merged it :)

**Comment by PascalPrecht** [comment]
@kentcdodds if you continue like this, we'll need to send you some swag. https://twitter.com/PascalPrecht/status/629577670393790464 #FriendsOfThoughtram

**Comment by kentcdodds** [comment]
Sweet! I'll email you my address :-)

**Comment by kentcdodds** [comment]
I would love to figure out how to install different packages per platform. I'll add an issue on the github repo and tweet with the question.

**Pull request merged**
